<a href="https://colab.research.google.com/github/amandaliram/pln_nlp_repository/blob/main/A05_RP04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Roteiro de Práticas 04:** Representação Numérica e a Maldição da Dimensionalidade

Este laboratório prático foca na transição do texto processado para a representação matemática vetorial. Até agora, nós limpamos e organizamos o texto, mas para que um algoritmo de machine learning possa trabalhar, precisamos converter essas palavras em números. Você aprenderá como as máquinas "leem" coleções de documentos através do modelo estatístico **Bag-of-Words (BoW)** e enfrentará o desafio da gestão de memória em matrizes de alta dimensionalidade.

### **1. Exemplo 1 – Aplicação do BoW**
  Execute o código abaixo para ver como um conjunto de documentos é transformado em um vocabulário e uma matriz de contagem.

In [ ]:
# importando a ferramenta que irá criar a representação numérica
from sklearn.feature_extraction.text import CountVectorizer

# criando um corpus de documentos que será usado para criação do vocabulário
documentos = [
    "gato e cachorro",
    "gato brinca com cachorro",
    "gato e rato",
    "Cachorro, gato e rato",
    "Gato",
    "Cachorro e rato"
]
# Criando um objeto para ser utilizado: transformar os documentos em vetores
vectorizer = CountVectorizer()

# Criando a matriz de contagem
X = vectorizer.fit_transform(documentos)
  # fit >>> cria um vocabulário das palavras
  # transforme >>> conta a frequencia de cada palavra no corpus

# Imprimindo a Matriz e o Vocabulário gerado
print(f"Vocabulario: {vectorizer.vocabulary_}")
  # realiza o mapeamento do vocabulário para um índice da matriz

print("Matriz BoW:")
print(X.toarray())
  # mostra a frequencia de cada palavra dentro da matriz

Vocabulario: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}
Matriz BoW:
[[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]
 [0 1 0 1 1]
 [0 0 0 1 0]
 [0 1 0 0 1]]


**Reflexão:** O que você nota sobre a palavra "Gato" e "gato"? Elas foram tratadas como a mesma coisa? Por que a pontuação (vírgula) foi ignorada?  

**Análise:** As palavras "Gato" com a primeira letra maiúscula e "gato" todo em minúsculo acabaram virando exatamente a mesma coisa na matriz final.    

*   **Tratamento igual:** Sim, foram tratadas como a mesma palavra. O `CountVectorizer` do scikit-learn possui um comportamento padrão que converte todo o texto para letras minúsculas (parâmetro `lowercase=True`) antes de contar.
*   **Pontuação ignorada:** A vírgula foi ignorada porque o tokenizador nativo do `CountVectorizer` usa uma regra que extrai apenas sequências de caracteres alfanuméricos. Qualquer símbolo ou pontuação é automaticamente descartado e funciona como um separador.

### **2. Exemplo 2 – BoW com Soneto de Fidelidade**
  Neste exemplo, vamos usar a técnica de Bag-of-Words para representar as estrofes do poema. A ideia é criar um vocabulário com todas as palavras únicas e, em seguida, contar a frequência de cada palavra em cada estrofe. O resultado será uma matriz onde as linhas representam as estrofes e as colunas representam a contagem de cada palavra do vocabulário.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Poema dividido em estrofes, para simular documentos
poema_estrofes = [
    "De tudo, ao meu amor serei atento antes",
    "E antes de mais nada, com tal zelo e sempre",
    "E sempre e tanto que em vossa presença sinta",
    "Que o vosso amor não tenha, o meu amor não tenha",
    "Diante de ti meu coração se fez, e meu corpo se fez, e minha alma se fez",
    "Em cada verso que escrevi para ti, em cada palavra que te disse"
]

# Criar o objeto para a representação BoW
vectorizer = CountVectorizer()

# Fit and transform no texto
matriz_bow = vectorizer.fit_transform(poema_estrofes)

print("--- Bag-of-Words (BoW) para o Soneto de Fidelidade ---")
print(f"\nVocabulário (palavra: índice): {vectorizer.vocabulary_}\n")
print("Matriz BoW (documentos x palavras):")
print(matriz_bow.toarray())

--- Bag-of-Words (BoW) para o Soneto de Fidelidade ---

Vocabulário (palavra: índice): {'de': 9, 'tudo': 33, 'ao': 3, 'meu': 16, 'amor': 1, 'serei': 26, 'atento': 4, 'antes': 2, 'mais': 15, 'nada': 18, 'com': 6, 'tal': 28, 'zelo': 37, 'sempre': 25, 'tanto': 29, 'que': 23, 'em': 12, 'vossa': 35, 'presença': 22, 'sinta': 27, 'vosso': 36, 'não': 19, 'tenha': 31, 'diante': 10, 'ti': 32, 'coração': 7, 'se': 24, 'fez': 14, 'corpo': 8, 'minha': 17, 'alma': 0, 'cada': 5, 'verso': 34, 'escrevi': 13, 'para': 21, 'palavra': 20, 'te': 30, 'disse': 11}

Matriz BoW (documentos x palavras):
[[0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
  0 0]
 [0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
  0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1
  0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0
  1 0]
 [1 0 0 0 0 0 0 1 1 1 1 0 0 0 3 0 2 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 1 0 0 0
  0 0]
 [0 0 0 0 0 

**Reflexão:** O que você nota sobre a palavra 'amor'? Ela tem um peso alto em todas as estrofes onde aparece. A matriz apenas conta a frequência, sem considerar a importância relativa da palavra no contexto do poema.

**Análise:** A palavra "amor" recebe um valor numérico muito alto na matriz simplesmente porque se repete muitas vezes, o que evidencia a principal fraqueza do modelo Bag-of-Words (BoW).

*   **Frequência absoluta:** O modelo conta apenas a quantidade de vezes que a palavra aparece. Ele não tem capacidade de interpretar se "amor" é a essência poética da estrofe ou apenas uma palavra de ligação, atribuindo peso máximo baseado puramente na sua repetição.
*   **Falta de contexto:** O algoritmo ignora completamente a semântica, a estrutura da frase e a importância relativa dos termos. Com isso, palavras muito frequentes acabam dominando a matriz e ofuscando termos mais raros que poderiam ser a verdadeira chave para entender o texto (uma limitação que algoritmos mais avançados, como o TF-IDF, buscam resolver).

### **Problema da dimensionalidade**
**2.1 Briefing do Problema (O Cenário)**   
Modelos de Aprendizado de Máquina são puramente matemáticos e não processam strings diretamente . O objetivo deste lab é converter uma pequena coleção de textos (Corpus) em uma **Matriz Termo-Documento**. Utilizaremos o seguinte dataset de strings para nossas experimentações:

In [ ]:
import numpy as np
import sys
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "o processamento de linguagem natural é incrível",
    "linguagem natural e inteligência artificial",
    "o processamento de linguagem e inteligência",
    "artificial incrível e natural",
    "inteligência é incrível"
]

**2.2 Módulo 1: Construção Manual do Vocabulário (Hard Way)**   
Nesta etapa, desconstruímos o corpus para isolar os **Types** (unidades únicas). Em Engenharia de Software, a ordem do vocabulário é o que define o "endereço" (índice) da feature na matriz.

In [ ]:
def extrair_vocabulario(docs):
    """
    Transforma uma lista de frases em uma lista ordenada de termos únicos.
    Foco: Normalização e Unicidade.
    """
    # 1. Normalização e Tokenização em uma única lista
    todos_os_tokens = []
    for frase in docs:
        tokens = frase.lower().split() # Tokenização bruta por espaço
        todos_os_tokens.extend(tokens)

    # 2. Garantia de Unicidade usando Set (Estrutura de Hash)
    vocab_set = set(todos_os_tokens)

    # 3. Ordenação Alfabética para consistência de índices
    vocab_ordenado = sorted(list(vocab_set))

    return vocab_ordenado

# Execução
vocabulario = extrair_vocabulario(corpus)
print(f"Vocabulário Ordenado ({len(vocabulario)} termos):")
print(vocabulario)

Vocabulário Ordenado (10 termos):
['artificial', 'de', 'e', 'incrível', 'inteligência', 'linguagem', 'natural', 'o', 'processamento', 'é']


**2.3 Módulo 2: Matriz Termo-Documento e a "Explosão Dimensional"**   
Agora, mapeamos cada documento para o espaço vetorial definido pelo vocabulário. Esta é uma **Matriz Densa**, onde alocamos memória para cada célula, mesmo que o valor seja zero.

In [ ]:
def construir_matriz_densa(docs, vocab):
    """
    Cria uma Matriz Termo-Documento (D x V) usando NumPy.
    Demonstra a alocação de memória para elementos nulos (zeros).
    """
    n_docs = len(docs)
    n_vocab = len(vocab)
    # Inicialização com zeros (8 bytes por célula usando int64)
    matriz = np.zeros((n_docs, n_vocab), dtype=np.int64)

    for i, frase in enumerate(docs):
        tokens_frase = frase.lower().split()
        for j, termo in enumerate(vocab):
            # Contagem de frequência
            matriz[i][j] = tokens_frase.count(termo)

    return matriz

matriz_final = construir_matriz_densa(corpus, vocabulario)
print("Matriz Termo-Documento (Representação Densa NumPy):")
print(matriz_final)

Matriz Termo-Documento (Representação Densa NumPy):
[[0 1 0 1 0 1 1 1 1 1]
 [1 0 1 0 1 1 1 0 0 0]
 [0 1 1 0 1 1 0 1 1 0]
 [1 0 1 1 0 0 1 0 0 0]
 [0 0 0 1 1 0 0 0 0 1]]


**2.4 Módulo 3: O Problema da Esparsidade (The Pythonic Way)**   
Em aplicações reais, o vocabulário atinge milhares de termos. Armazenar uma matriz onde 99% das células são zero em formato denso causa o erro de `MemoryError`. Aqui, usaremos matrizes esparsas **CSR (Compressed Sparse Row) **do SciPy via `scikit-learn`.

In [ ]:
# 1. Vetorização Profissional
vectorizer = CountVectorizer()
X_esparso = vectorizer.fit_transform(corpus)

# 2. Conversão para Denso apenas para fins de comparação didática
X_denso = X_esparso.toarray()

# 3. Prova Matemática de Desperdício (RAM)
# Para matrizes esparsas, somamos os arrays de dados, índices e ponteiros
memoria_esparsa = X_esparso.data.nbytes + X_esparso.indptr.nbytes + X_esparso.indices.nbytes
memoria_densa = X_denso.nbytes

# 4. Cálculo de Esparsidade
total_celulas = X_denso.size
zeros = total_celulas - np.count_nonzero(X_denso)
percentual_zeros = (zeros / total_celulas) * 100

print("--- Relatório de Performance de Memória ---")
print(f"Memória RAM (Matriz Densa): {memoria_densa} bytes")
print(f"Memória RAM (Matriz Esparsa): {memoria_esparsa} bytes")
print(f"Eficiência de Memória: {((memoria_densa - memoria_esparsa) / memoria_densa) * 100:.2f}% de economia")
print(f"Porcentagem de Esparsidade: {percentual_zeros:.2f}% de zeros na matriz")

--- Relatório de Performance de Memória ---
Memória RAM (Matriz Densa): 280 bytes
Memória RAM (Matriz Esparsa): 240 bytes
Eficiência de Memória: 14.29% de economia
Porcentagem de Esparsidade: 48.57% de zeros na matriz


## **3. Desafio de Conclusão: O Dataset do Kaggle**

Agora é com o seu Squad. Siga os passos para validar seu conhecimento em um cenário real:

1.  **Escolha do Dataset:** Acesse o Kaggle e baixe um dataset de reviews (ex: *Amazon Reviews* ou *Olist*).
2.   **Carga e Limpeza:** Use o pipeline de limpeza desenvolvido na Aula 03 (Regex e Tokenização).
2.  **Vetorização:** Aplique o CountVectorizer no dataset completo.
2.  **Análise de Stress:** Tente converter a matriz resultante para o formato denso (.toarray()).  
  *Aviso:* Se o dataset for grande, sua memória RAM irá estourar.
2.   **Entregável:** Documente no seu Jupyter Notebook qual foi a economia de memória em Megabytes ao utilizar a matriz esparsa em vez da densa.

### 🚀 **Desafio de conclusão escolhido:** Análise de Stress e Vetorização (Amazon Reviews)

**Objetivo:** Validar o pipeline de limpeza em um cenário real e documentar o impacto na gestão de memória (Esparsa vs. Densa) utilizando o modelo estatístico Bag-of-Words (BoW).

**Dataset Escolhido:** `abdallahwagih/amazon-reviews` (Cell Phones & Accessories).
*Nota: Este dataset contém avaliações em inglês sobre celulares e acessórios, permitindo testar a eficiência matemática e computacional de pipelines de PLN em contexto de mercado.*

In [ ]:
# ==============================================================================
# PASSO 1: Download do Dataset (Otimizado com kagglehub)
# ==============================================================================
!pip install kagglehub -q

import kagglehub

print("--- BAIXANDO O DATASET DA AMAZON ---")
path = kagglehub.dataset_download("abdallahwagih/amazon-reviews")

print(f"✅ Dataset baixado e extraído com sucesso!")
print(f"📂 Caminho dos arquivos: {path}")

--- BAIXANDO O DATASET DA AMAZON ---
Using Colab cache for faster access to the 'amazon-reviews' dataset.
✅ Dataset baixado e extraído com sucesso!
📂 Caminho dos arquivos: /kaggle/input/amazon-reviews


### 📥 Carga dos Dados e Pipeline de Limpeza
Nesta etapa, carregamos o arquivo `.csv` extraído e isolamos a coluna que contém os textos das avaliações. Utilizaremos nossa função de limpeza profissional para normalizar os dados, removendo lixos, URLs e pontuações indesejadas antes de aplicar o modelo BoW.

In [ ]:
# ==============================================================================
# PASSO 2: Carga, Limpeza e Amostragem (Busca Profunda por JSON)
# ==============================================================================
import pandas as pd
import numpy as np
import re
import nltk
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
import glob
import os

nltk.download('punkt_tab', quiet=True)

# Nosso pipeline de limpeza focado no texto bruto
def tokenizer_personalizado(texto):
    if not isinstance(texto, str):
        return []
    texto = texto.lower()
    texto = re.sub(r'<.*?>', ' ', texto)
    texto = re.sub(r'http\S+', '', texto)
    texto = re.sub(r'[^\w\s]', ' ', texto)
    return word_tokenize(texto)

# ==========================================
# CORREÇÃO: Busca por arquivos JSON
# ==========================================
arquivos_json = glob.glob(os.path.join(path, '**', '*.json'), recursive=True)

if not arquivos_json:
    print(f"⚠️ Nenhum arquivo .json encontrado no caminho: {path}")
    print("Arquivos detectados:")
    for root, dirs, files in os.walk(path):
        for f in files:
            print(f" -> {os.path.join(root, f)}")
    raise FileNotFoundError("JSON não localizado. Verifique os arquivos acima.")

# Pega o primeiro JSON encontrado na varredura
arquivo_json = arquivos_json[0]

# Carregando o dataframe (lines=True é essencial para JSON Lines da Amazon)
df_amazon = pd.read_json(arquivo_json, lines=True)

# A coluna de avaliações geralmente se chama 'review' ou 'body'.
# Se não achar, pega a primeira coluna de texto do arquivo.
colunas_texto = df_amazon.select_dtypes(include=['object']).columns
coluna_alvo = 'reviewText' if 'reviewText' in df_amazon.columns else ('body' if 'body' in df_amazon.columns else ('review' if 'review' in df_amazon.columns else colunas_texto[0]))

# Limitamos a 15.000 amostras para o Teste de Stress
corpus_amazon = df_amazon[coluna_alvo].dropna().astype(str).tolist()[:15000]

print(f"📦 Sucesso! Arquivo '{os.path.basename(arquivo_json)}' carregado.")
print(f"📊 Foram carregadas {len(corpus_amazon)} avaliações para o Teste de Stress.")

📦 Sucesso! Arquivo 'Cell_Phones_and_Accessories_5.json' carregado.
📊 Foram carregadas 15000 avaliações para o Teste de Stress.


### 🧮 Vetorização e Análise de Stress (BoW)
Vamos aplicar o `CountVectorizer` usando nosso pipeline. Em seguida, forçaremos a conversão da Matriz Esparsa nativa para a Matriz Densa (`.toarray()`) e calcularemos, em Megabytes, o custo de hardware gerado pelos Zeros (esparsidade).

In [ ]:
# ==============================================================================
# PASSO 3: Vetorização e Gestão de Memória (Stress Test)
# ==============================================================================
print("⏳ Iniciando a vetorização e tokenização completa (Aguarde alguns segundos)...")

vectorizer = CountVectorizer(tokenizer=tokenizer_personalizado, token_pattern=None)
X_esparso = vectorizer.fit_transform(corpus_amazon)
vocab_amazon = vectorizer.get_feature_names_out()

bytes_esparso = X_esparso.data.nbytes + X_esparso.indptr.nbytes + X_esparso.indices.nbytes
mb_esparso = bytes_esparso / (1024 * 1024)

print("🧨 Convertendo para Matriz Densa (Isso testará os limites da sua RAM)...")
X_denso = X_esparso.toarray()
mb_denso = X_denso.nbytes / (1024 * 1024)

economia_mb = mb_denso - mb_esparso
economia_percentual = (economia_mb / mb_denso) * 100
esparsidade = 100 - (np.count_nonzero(X_denso) / X_denso.size * 100)

⏳ Iniciando a vetorização e tokenização completa (Aguarde alguns segundos)...
🧨 Convertendo para Matriz Densa (Isso testará os limites da sua RAM)...


### 📊 Entregável: Relatório Executivo de Economia em Nuvem
Abaixo está o relatório gerado dinamicamente para validar as decisões arquiteturais.

In [ ]:
# ==============================================================================
# PASSO 4: Impressão do Relatório Executivo
# ==============================================================================
print("="*70)
print("🚀 RELATÓRIO FINAL: AMAZON REVIEWS (STRESS TEST & MEMÓRIA)")
print("="*70)
print(f"📱 Domínio: Cell Phones & Accessories")
print(f"📄 Total de Avaliações Processadas: {len(corpus_amazon)}")
print(f"🔤 Vocabulário Único (Types/Features): {len(vocab_amazon)} palavras")
print(f"🕳️ Nível de Esparsidade da Matriz: {esparsidade:.2f}% (Células preenchidas com ZERO)")
print("-" * 70)
print(f"🔴 Memória RAM Exigida (Matriz Densa): {mb_denso:.2f} Megabytes (MB)")
print(f"🟢 Memória RAM Exigida (Matriz Esparsa): {mb_esparso:.4f} Megabytes (MB)")
print("-" * 70)
print(f"🏆 ECONOMIA TOTAL DE MEMÓRIA (Cloud Saving): {economia_mb:.2f} Megabytes (MB)")
print(f"📉 Redução percentual de carga computacional: {economia_percentual:.2f}%")
print("="*70)
print("\n📝 CONCLUSÃO TÉCNICA (Justificativa para o Cliente):")
print(f"Ao lidar com {len(corpus_amazon)} avaliações textuais, o uso de Matrizes Densas")
print("exigiria a alocação de milhões de blocos de memória para armazenar o número '0'")
print("(termos ausentes). O formato esparso contornou esse problema arquitetural,")
print("garantindo estabilidade no servidor e redução massiva de custos em Cloud.")

🚀 RELATÓRIO FINAL: AMAZON REVIEWS (STRESS TEST & MEMÓRIA)
📱 Domínio: Cell Phones & Accessories
📄 Total de Avaliações Processadas: 15000
🔤 Vocabulário Único (Types/Features): 25412 palavras
🕳️ Nível de Esparsidade da Matriz: 99.73% (Células preenchidas com ZERO)
----------------------------------------------------------------------
🔴 Memória RAM Exigida (Matriz Densa): 2908.17 Megabytes (MB)
🟢 Memória RAM Exigida (Matriz Esparsa): 11.6907 Megabytes (MB)
----------------------------------------------------------------------
🏆 ECONOMIA TOTAL DE MEMÓRIA (Cloud Saving): 2896.48 Megabytes (MB)
📉 Redução percentual de carga computacional: 99.60%

📝 CONCLUSÃO TÉCNICA (Justificativa para o Cliente):
Ao lidar com 15000 avaliações textuais, o uso de Matrizes Densas
exigiria a alocação de milhões de blocos de memória para armazenar o número '0'
(termos ausentes). O formato esparso contornou esse problema arquitetural,
garantindo estabilidade no servidor e redução massiva de custos em Cloud.
